version: '3.3'
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
    # api:
    #     image: api
    #     ports:
    #         - '3333:3333'
    #     depends_on:
    #         - db
    # triage:
    #     image: triage
    #     ports:
    #         - '3335:3335'

    # publisher:
    #     image: publisher
    #     environment:
    #         - apiPath=http://api:3333
    #     ports:
    #         - '3334:3334'
    #     env_file:
    #         - .env
    # api:
    #     image: api
    #     ports:
    #         - '3333:3333'
    #     env_file:
    #         - .env
    # triage:
    #     image: triage
    #     ports:
    #         - '3335:3335'
    #     env_file:
    #         - .env
