---
openapi: 3.0.0
info:
  title: Triage
  description: The Triage API description
  version: '1.0'
  contact: {}
tags:
- name: Triage
  description: ''
servers:
- url: 'https://triage-undpjtf-iverify-honduras-js.leman.un-icc.cloud/'
components:
  schemas:
    SubmitStoryDto:
      type: object
      properties:
        url:
          type: string
        content:
          type: string
        secret:
          type: string
      required:
      - url
      - content
      - secret
paths:
  "/triage/submit-story":
    post:
      operationId: AppController_submitStory
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SubmitStoryDto"
      responses:
        '201':
          description: ''
      tags:
      - Submit story
