---
openapi: 3.0.0
info:
  title: Swagger
  description: The Publisher API description
  version: '1.0'
  contact: {}
tags:
- name: Swagger
  description: ''
servers:
- url: 'https://publisher-undpjtf-iverify-honduras-js.leman.un-icc.cloud/'
components:
  schemas:
    PublishReportDto:
      type: object
      properties:
        event:
          type: string
        data:
          type: object
      required:
      - event
      - data
paths:
  "/publisher/publish-webhook":
    post:
      operationId: AppController_punlishReportWebhook
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PublishReportDto"
      responses:
        '201':
          description: ''
      tags:
      - Publish Report
  "/publisher/publish-test-endpoint":
    post:
      operationId: AppController_punlishTestEndpoint
      parameters: []
      responses:
        '201':
          description: ''
